export type * as AcademicEducationResponse from './academicEducation'
export type * as AdditionalEducationResponse from './additionalEducation'
export type * as EventsResponse from './events'
export type * as EventMediasResponse from './eventMedias'
export type * as HomeSectionsResponse from './homeSections'
export type * as ProfileResponse from './profile'
export type * as SocialMediasResponse from './socialMedias'
export type * as WorksResponse from './work'
