import type { Metadata } from 'next'
import { Ubuntu } from 'next/font/google'

import { Navbar } from '@/components/navbar'
import { Toaster } from '@/components/ui/toaster'
import './globals.css'

const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={ubuntu.className}>
      <body className='bg-primary relative'>
        <Navbar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
